import React, { useEffect } from 'react';
import Head from 'next/head';
import { MainLayout } from '../components/layout/MainLayout';
import { useDashboardStore } from '../store/dashboardStore';
import { Widget } from '../types';
import { Layout } from 'react-grid-layout';

// Default widgets for new users
const defaultWidgets: Widget[] = [
  {
    i: 'widget-1',
    type: 'todays_schedule',
    title: "Today's Schedule",
  },
  {
    i: 'widget-2',
    type: 'daily_stats',
    title: 'Daily Statistics',
  },
  {
    i: 'widget-3',
    type: 'quick_actions',
    title: 'Quick Actions',
  },
  {
    i: 'widget-4',
    type: 'outstanding_items',
    title: 'Outstanding Items',
  },
];

const defaultLayout: Layout[] = [
  { i: 'widget-1', x: 0, y: 0, w: 6, h: 3, minW: 4, minH: 2 },
  { i: 'widget-2', x: 6, y: 0, w: 3, h: 2, minW: 3, minH: 2 },
  { i: 'widget-3', x: 9, y: 0, w: 3, h: 2, minW: 2, minH: 2 },
  { i: 'widget-4', x: 0, y: 3, w: 4, h: 2, minW: 3, minH: 2 },
];

export default function Home() {
  const widgets = useDashboardStore((state) => state.widgets);
  const setWidgets = useDashboardStore((state) => state.setWidgets);
  const loadFromLocalStorage = useDashboardStore((state) => state.loadFromLocalStorage);

  useEffect(() => {
    // Try to load from localStorage first
    loadFromLocalStorage();

    // If no widgets found, use default layout
    const savedWidgets = localStorage.getItem('dashboardWidgets');
    if (!savedWidgets || JSON.parse(savedWidgets).length === 0) {
      setWidgets(defaultWidgets, defaultLayout);
    }
  }, [loadFromLocalStorage, setWidgets]);

  return (
      <>
        <Head>
          <title>Outsquare EHR Canvas Dashboard</title>
          <meta
              name="description"
              content="Customizable medical dashboard for Outsquare EHR"
          />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <MainLayout />
      </>
  );
}


// import Head from "next/head";
// import Image from "next/image";
// import { Geist, Geist_Mono } from "next/font/google";
// import styles from "@/styles/Home.module.css";
//
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });
//
// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });
//
// export default function Home() {
//   return (
//     <>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <div
//         className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
//       >
//         <main className={styles.main}>
//           <Image
//             className={styles.logo}
//             src="/next.svg"
//             alt="Next.js logo"
//             width={180}
//             height={38}
//             priority
//           />
//           <ol>
//             <li>
//               Get started by editing <code>src/pages/index.tsx</code>.
//             </li>
//             <li>Save and see your changes instantly.</li>
//           </ol>
//
//           <div className={styles.ctas}>
//             <a
//               className={styles.primary}
//               href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//               target="_blank"
//               rel="noopener noreferrer"
//             >
//               <Image
//                 className={styles.logo}
//                 src="/vercel.svg"
//                 alt="Vercel logomark"
//                 width={20}
//                 height={20}
//               />
//               Deploy now
//             </a>
//             <a
//               href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//               target="_blank"
//               rel="noopener noreferrer"
//               className={styles.secondary}
//             >
//               Read our docs
//             </a>
//           </div>
//         </main>
//         <footer className={styles.footer}>
//           <a
//             href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <Image
//               aria-hidden
//               src="/file.svg"
//               alt="File icon"
//               width={16}
//               height={16}
//             />
//             Learn
//           </a>
//           <a
//             href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <Image
//               aria-hidden
//               src="/window.svg"
//               alt="Window icon"
//               width={16}
//               height={16}
//             />
//             Examples
//           </a>
//           <a
//             href="https://nextjs.org?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <Image
//               aria-hidden
//               src="/globe.svg"
//               alt="Globe icon"
//               width={16}
//               height={16}
//             />
//             Go to nextjs.org →
//           </a>
//         </footer>
//       </div>
//     </>
//   );
// }
